### ISSUE TITLE
[Question] Support for Pact?

### ISSUE THREAD

**Issue by darwin67** [dashbitco/mox#105]
Hello,

When I search for `elixir contract testing`, this library and hammox are always the first ones to show up.
After reading the docs, mox seems like a good library to use for testing external dependencies to some degree, but I don't see it as well covered as [Pact](https://docs.pact.io/) for use case like microservices.

Would it make sense to have mox support pact?

**Comment by josevalim** [comment]
Hi Darwin, we have no plans to support something like Pact but someone can hopefully build something like that on top of projects like Mox and Bypass (or as its own project).
