### ISSUE TITLE
hexdocs isn't up to date - the content is wrong.

### ISSUE THREAD

**Issue by andyduong1920** [dashbitco/mox#111]
Hi 👋 

Not sure what happened but the document on [hexdocs ](https://hexdocs.pm/mox/Mox.html#module-global-mode)is not correct. It should contain the **doesn't** following the current [master codebase](https://github.com/dashbitco/mox/blob/master/lib/mox.ex#L163)

![image](https://user-images.githubusercontent.com/11751745/109468525-48850d00-7a9f-11eb-8f7e-6431f1b8084a.png)

**Comment by josevalim** [comment]
New version published, thanks!

**Comment by andyduong1920** [comment]
Confirm it's working now 👏

![image](https://user-images.githubusercontent.com/11751745/109471001-b848c700-7aa2-11eb-8d21-5353760ebeff.png)
