### ISSUE TITLE
Add pid to test context

### ISSUE THREAD

**Issue by LostKobrakai** [dashbitco/mox#114]
I'm often doing mox expectations like this:
```
test = self()
expect(MyMock, :reset, fn ->
  send(test, :reset)
  :ok
end)
…
assert_receive :reset, 100
```

This allows me to keep the order of arrange -> act -> assert and also allows for more flexibility in assertions (e.g. certain order between multiple mocks). The part of adding the `test = self()` always feels kind of verbose, I'm wondering if the Mox setup functions could add the current tests pid into the test context. Then it could be fetch with `test "label", %{pid: test}`.

**Comment by josevalim** [comment]
You can do that in a CaseTemplate, I don't quite think it is part of Mox. :)
