### ISSUE TITLE
Module not available

### ISSUE THREAD

**Issue by michaelst** [dashbitco/mox#127]
When running on a clean compile we are getting this error, if I remove all of the defmocks from mocks.ex then compile and add them back after it works. Currently running on 1.13.4-otp-24 and 24.3.3, but have tried multiple version combos with the same result. It fails because `Code.ensure_compiled(Genesis.Behaviour.BankAccount)` returns `{:error, :unavailable}`

```
== Compilation error in file test/support/mocks.ex ==
** (ArgumentError) module Genesis.Behaviour.BankAccount is not available, please pass an existing module to :for
    (mox 1.0.1) lib/mox.ex:361: Mox.validate_behaviour!/1
    (mox 1.0.1) lib/mox.ex:383: anonymous fn/2 in Mox.generate_compile_time_dependency/1
    (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mox 1.0.1) lib/mox.ex:382: Mox.generate_compile_time_dependency/1
    (mox 1.0.1) lib/mox.ex:349: Mox.defmock/2
    test/support/mocks.ex:13: (file)
```

**Comment by josevalim** [comment]
Looking at the code, this can only happen due to a compiler bug. Is there anything special happening at how the behavior is defined? Can you guarantee it is a single module in a single file and only the callbacks are defined? No structs and no functions? Would the issue persist with only that?

**Comment by michaelst** [comment]
turns out we had some structs referenced in our callbacks we changed those and it removed the issue, sorry for the false alarm

```
@callback update_acquiring_chargeback(String.t(), map) :: {:ok, %AcquiringChargeback{}} | {:error, term}
```

changed to this 

```
@callback update_acquiring_chargeback(String.t(), map) :: {:ok, AcquiringChargeback.t()} | {:error, term}
```
