### ISSUE TITLE
[proposal] Include the error location in the error message.

### ISSUE THREAD

**Issue by dkuku** [dashbitco/mox#139]
Hey, I'm using Mox/Hammox intensively and I have one pain point when working in phoenix controllers.
The stack trace is often too deep and it's not showing me the actual file which is always at the end of the stack trace.
I can change the backtrace depth to include it but then I have even more garbage on the screen and I need to do it for every project I work on.
Any chance to include the actual file and line in the error or make the error somehow configurable ?

**Comment by whatyouhide** [comment]
@josevalim will correct me if I'm wrong, but I think this is hard to do because the `expect` and `stub` and `verify!` functions are all functions and not macros, so they don't really know where they're called from.

Can you show an example of a long stacktrace, and I can try to help figuring out if we can improve the situation? 🙃

**Comment by dkuku** [comment]
This is an example with stack trace already extended - normally It's few lines shorter.
```
  3) test update/2 customer blocked (MyAppWeb.MeetingControllerTest)
     apps/my_app_web/test/my_app_web/controllers/meeting_controller_test.exs:677
     ** (Mox.UnexpectedCallError) no expectation defined for Platform.RpcClients.CustomersMock.get_customer_ids_by_auth_ids/1 in process #PID<0.6742.0> with args [%Rpc.Customers.V1.GetCustomerIdsByAuthIdsRequest{auth_ids: [16768], include_deleted: true, provider_id: nil}]
     code: |> patch(meeting_path(conn, :update, meeting), encoded_params)
     stacktrace:
       (mox 1.0.2) lib/mox.ex:795: Mox.__dispatch__/4
       (platform 0.0.1) lib/customers/customers_rpc.ex:176: anonymous fn/3 in Platform.Customers.CustomersRPC.get_customer_ids_by_auth_ids/2
       (elixir 1.13.3) lib/enum.ex:4475: Enumerable.List.reduce/3
       (elixir 1.13.3) lib/stream.ex:931: Stream.do_list_transform/7
       (elixir 1.13.3) lib/enum.ex:2442: Enum.reduce_while/3
       (platform 0.0.1) lib/customers/customers_rpc.ex:169: Platform.Customers.CustomersRPC.get_customer_ids_by_auth_ids/2
       (my_app 0.0.1) lib/legacy/marketplace/apis/get_meeting_api.ex:10: MyApp.Legacy.Marketplace.GetMeetingAPI.call/2
       (my_app 0.0.1) lib/legacy/marketplace/apis/reschedule_meeting_api.ex:23: MyApp.Legacy.Marketplace.RescheduleMeetingAPI.call/3
       (my_app 0.0.1) lib/legacy/marketplace/marketplace.ex:569: MyApp.Legacy.Marketplace.reschedule_meeting/3
       (my_app_web 0.0.1) lib/controllers/meeting_controller.ex:19: MyAppWeb.MeetingController.update/2
       (my_app_web 0.0.1) lib/controllers/meeting_controller.ex:1: MyAppWeb.MeetingController.action/2
       (my_app_web 0.0.1) lib/controllers/meeting_controller.ex:1: MyAppWeb.MeetingController.phoenix_controller_pipeline/2
       (phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
       (my_app_web 0.0.1) lib/plug/router.ex:246: anonymous fn/4 in MyAppWeb.APIGatewayRouter.dispatch/2
       (telemetry 0.4.3) /Users/kuku/system/apps/my-app-umbrella/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
       (my_app_web 0.0.1) lib/plug/router.ex:242: MyAppWeb.APIGatewayRouter.dispatch/2
       (my_app_web 0.0.1) lib/api_gateway_router.ex:1: MyAppWeb.APIGatewayRouter.plug_builder_call/2
       (my_app_web 0.0.1) lib/endpoint.ex:1: MyAppWeb.Endpoint.plug_builder_call/2
       (my_app_web 0.0.1) lib/endpoint.ex:1: MyAppWeb.Endpoint."call (overridable 3)"/2
       (my_app_web 0.0.1) lib/endpoint.ex:1: MyAppWeb.Endpoint.call/2
       (phoenix 1.5.13) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/my_app_web/controllers/meeting_controller_test.exs:713: (test)
```

**Comment by dkuku** [comment]
And I'm mostly interested in the last line here - where it exactly failed.

**Comment by whatyouhide** [comment]
@dkuku hi, I was triaging the open issues here. So, from the stacktrace you posted above, my takeaway is that the mock itself is failing on `lib/customers/customers_rpc.ex:176` (first line of the stacktrace) and the failing test is `apps/my_app_web/test/my_app_web/controllers/meeting_controller_test.exs:677` (first line after error message). So, yeah the last line is the line in the specific test where it all began, but the long stacktrace is not Mox's fault. Mox cannot know that that's where the call came from originally, or rather, you are doing already the right thing which is extending the backtrace depth.

Thanks anyways!
