### ISSUE TITLE
Test scenario scoping with real implementation fallback

### ISSUE THREAD

**Issue by pepicrft** [dashbitco/mox#144]
👋🏼 Hi,

First of all, thanks for building this wonderful package. I started using it in a personal project and also built a [small utility](https://github.com/glossia/application_module) to improve the the ergonomics a little bit.

Once thing that I noticed when I started using the library is that **setting the mock in the application environment affects all the tests in the suite.** This might be undesirable in some cases like when implementing integration tests where the code execution traverses several modules and we expect the real implementation to be used.

The above made me think whether it'd make sense to extend Mox to support scoping the test to a particular test execution. I noticed in the implementation that internally uses a `Genserver` to associate the expectations with a test, so we could follow a similar approach to associate a mock or a real implementation to a particular test. Perhaps something along the lines of:

```elixir
# test_helper.exs
Mox.defmock(WeatherBehaviourMock, for: WeatherBehaviour, default: Weather)
Application.put_env(:bound, :weather, WeatherBehaviourMock)

# my_test.exs
defmodule MyTest do
  use ExUnit.Case, async: true

  test "foo" do
    Mox.usemock()
    # Mox.usedefault()
  end
end
```

Do you think something like this should be scope of Mox? If so, I'd be happy to go ahead with the implementation with some advise from your side 😊

**Comment by josevalim** [comment]
Hi @pepicrft! I believe you can use stub_with in your tests setup to provide a default implementation that will be used by other tests. :)

**Comment by pepicrft** [comment]
❤️ You haven't missed any case! Thanks @josevalim 🙏🏼
