### ISSUE TITLE
Document the send/assert_receive methodology

### ISSUE THREAD

**Issue by leggebroten** [dashbitco/mox#93]
Avoiding race conditions in tests of separate processes is imperative and the technique suggested in your docs is great.  It's declarative and avoids failure prove `Process.sleep` solutions so often taken

https://github.com/dashbitco/mox/blob/d4fbb04622ca2be705e2c476ead1d0044427524b/lib/mox.ex#L202

But I liked even more, the solution you implemented in the tests.
Not only does it solve the race condition issues from the current example, but illustrates how to assert data passed to the `expect`
https://github.com/dashbitco/mox/blob/d4fbb04622ca2be705e2c476ead1d0044427524b/test/mox_test.exs#L643
https://github.com/dashbitco/mox/blob/d4fbb04622ca2be705e2c476ead1d0044427524b/test/mox_test.exs#L654-L656

Would you be OK with me submitting a PR for the documentation change?

**Comment by josevalim** [comment]
A PR is great. Note we already mention something along these lines here: https://github.com/dashbitco/mox/blob/master/lib/mox.ex#L173

**Comment by leggebroten** [comment]
Exactly. 
I was just going to enhance that section with the example usage you have in the Mox test suites to assert values passed to the call.  (from issue description above)

Until seeing that example, I was doing the assertion within the `expect` declaration which obviously causes issues when the assertions fail.

Also, why does the current example recommend passing a ref but the tests don't do that?
What's the advantage?

https://github.com/dashbitco/mox/blob/d4fbb04622ca2be705e2c476ead1d0044427524b/lib/mox.ex#L199
https://github.com/dashbitco/mox/blob/d4fbb04622ca2be705e2c476ead1d0044427524b/lib/mox.ex#L202
https://github.com/dashbitco/mox/blob/d4fbb04622ca2be705e2c476ead1d0044427524b/lib/mox.ex#L208

**Comment by josevalim** [comment]
Refs help guarantee uniqueness since they are unique, so you don’t match on another message by accident.

It should be fine to do the assertion inside the expect though, unless multiple processes are involved, which that section covers.

**Comment by leggebroten** [comment]
My server under test is trapping exit to clean up resources. 
 
I was running into race condition where, if the assert inside the `expect` failed, the Mox expectation would be removed before the process under test hit the `terminate` function, leading to "missing expectation" error being logged that obscured the real issue

**Comment by josevalim** [comment]
Yeah, exactly. That section is for you then. :) But further improvements are welcome!
